apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
#Pods number replicates
  replicas: 1
  #Define how the Deployment identify the pods that it could manage
  selector: 
    matchLabels:
     app: mysql
     #pod template specification
  template:
    metadata:
    #define teh labels for all pods
      labels:
        app: mysql       
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          #open the port to allow send and receive traffic in teh container
          ports:
            - containerPort: 3306
            #read envars from secret file
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
          #This is the path in the container on which the mounting will take place.
#            - mountPath: /var/lib/mysql2/data
#              name: mysql-volume
     #       - mountPath: /docker-entrypoint-initdb.d
     #         name : init-script
      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-claim
     #   - name: init-script
     #     configMap:
     #        name: mysql-init-script-configmap