#object that store enviroments variables that could be have sensitive data like a password
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    #meant that we can use arbitrary key pair values
type: Opaque
data:
 # POSTGRES_DB: cG9zdGdyZXM=
 # POSTGRES_USER: cG9zdGdyZXM=
 # POSTGRES_PASSWORD: cXdlcnR5
  # MYSQL_DATABASE: ZGIK
  # MYSQL_USER: dXNlcgo=
  # MYSQL_PASSWORD: cGFzc3dvcmQK
  # MYSQL_ROOT_PASSWORD: cGFzc3dvcmQK
  MYSQL_DATABASE: ZGI=
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
