kind: Service
apiVersion: v1
metadata:
  name: mysql-service
  labels:
    app: mysql
spec: 
  clusterIP: 10.96.1.2 
  ipFamilies:
  - IPv4
  ports:
  - name: mysql
    port: 3306
    nodePort : 30432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: mysql