# Use root/example as user/password credentials
version: '3.7'

services:

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
       - env_qa  
    ports:
      - 3306:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d

  pizzaApp:
  #  entrypoint: "true"
    image: billingapp:prod3
    container_name: pizzaApp
    build: 
      context: ./jars
      args: 
        message: itworkeddockerProd
        datasource: db
       
    ports:
       - 8086:8086
    networks:
       - env_qa  

    depends_on:
       - db
  
networks:
  env_qa:
    driver: bridge  



# Names our volume
volumes:
  my-db:
